name: bash_unit CI
on:
  push:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install Ubuntu dependencies with sudo apt install -y
      run: sudo apt install -y gawk
    - name: Unit testing with bash_unit
      run: ./bash_unit tests/test*

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install MacOS dependencies with brew install
      run: brew install gawk
    - name: Unit testing with bash_unit
      run: ./entrypoint.sh tests
